// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgqpRdu-Myl4K3J2YmDx1A5gKn980RytE',
    appId: '1:183829261962:web:c1850aec3665f6fef18773',
    messagingSenderId: '183829261962',
    projectId: 'drinkingapp-84ac5',
    authDomain: 'drinkingapp-84ac5.firebaseapp.com',
    storageBucket: 'drinkingapp-84ac5.firebasestorage.app',
    measurementId: 'G-5ZTBCG8VPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5D15XD86l2iLY3rwS1eTwrrnabLMzbQw',
    appId: '1:183829261962:android:31766e0d17924534f18773',
    messagingSenderId: '183829261962',
    projectId: 'drinkingapp-84ac5',
    storageBucket: 'drinkingapp-84ac5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuka69kKBaoWBNd8Bf6iJtU5XMJQ53y-U',
    appId: '1:183829261962:ios:f8fac081218afae5f18773',
    messagingSenderId: '183829261962',
    projectId: 'drinkingapp-84ac5',
    storageBucket: 'drinkingapp-84ac5.firebasestorage.app',
    iosBundleId: 'com.example.4drinkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuka69kKBaoWBNd8Bf6iJtU5XMJQ53y-U',
    appId: '1:183829261962:ios:f8fac081218afae5f18773',
    messagingSenderId: '183829261962',
    projectId: 'drinkingapp-84ac5',
    storageBucket: 'drinkingapp-84ac5.firebasestorage.app',
    iosBundleId: 'com.example.4drinkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgqpRdu-Myl4K3J2YmDx1A5gKn980RytE',
    appId: '1:183829261962:web:14389cb8547f3a4bf18773',
    messagingSenderId: '183829261962',
    projectId: 'drinkingapp-84ac5',
    authDomain: 'drinkingapp-84ac5.firebaseapp.com',
    storageBucket: 'drinkingapp-84ac5.firebasestorage.app',
    measurementId: 'G-DDF1EC6E1T',
  );
}
